name: Build and Deploy Flask App to Azure Web App

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Adjust Python version if necessary

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Archive files
      run: zip -r app.zip .

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: shyraq  # Replace with your Web App name
        slot-name: production
        package: ./app.zip
